## Name: Sougata Sen
### Reg: 24-27-37
### Course: M.Tech in Data Science

# Question 1

### (a)

In [1]:
import numpy as np

var1 = np.arange(30)
print(var1)
var1.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


(30,)

### (b)

In [2]:
var2 = var1.reshape(3,10)
print(var2)
print(var2.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
(3, 10)


### (c)

In [3]:
# creating array of size 2 with each element as array of 3x5
var3 = var1.reshape(2,3,5)
print(var3)
print(var3.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
(2, 3, 5)


In [4]:
# (d)
var2[1, 0] = -1
print(var2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [-1 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [5]:
# (d)
print("var1: \n", var1)
print("var3: \n", var3)

var1: 
 [ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
var3: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [-1 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# (d) explanation
Clearly the value of var1 and var3 has also changed. This proves that the reshape function returns a view but not a copy. So when we changed the element in var2, the corresponding element in var1 and var3 also changed because on changing the element in var2, we actually changed the element in the original array i.e. var1 and hence it's all the reshaped variables will also change accordingly.

### (e)

In [6]:
print("Var3: \n", var3)
x = var3.sum(axis=1)
y = var3.sum(axis=2)
z = var3.sum(axis=(0, 2))
print("i. Sum of var3 over 2nd dimension:\n", x)
print("ii. Sum of var3 over 3rd dimension:\n", y)
print("iii. Sum of var3 over 1st and 3rd dimension:\n",z)


Var3: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [-1 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
i. Sum of var3 over 2nd dimension:
 [[ 4 18 21 24 27]
 [60 63 66 69 72]]
ii. Sum of var3 over 3rd dimension:
 [[ 10  35  49]
 [ 85 110 135]]
iii. Sum of var3 over 1st and 3rd dimension:
 [ 95 145 184]


### (f)

In [7]:
print("Var2:\n", var2)
print("i. Second row:\n", var2[1:2])
print("ii. last column:\n", var2[:,-1])
print("iii. Top right 2x2 sub-matrix:\n", var2[:2, -2:])

Var2:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [-1 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
i. Second row:
 [[-1 11 12 13 14 15 16 17 18 19]]
ii. last column:
 [ 9 19 29]
iii. Top right 2x2 sub-matrix:
 [[ 8  9]
 [18 19]]


# Question2

### (a)

In [8]:
ar = np.arange(0, 10)
print(ar)
vector_ar = ar + 1
print(vector_ar)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]


### (b)

In [9]:
A = ar + ar.reshape(10,1)
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


### (c)

In [10]:
import numpy.random as npr
data = np.exp(npr.randn(50, 5))

### (d)

In [11]:
print(data)

[[ 0.87063366  1.9144133   0.82938996  2.53321452  0.76857993]
 [ 3.92847858  1.37580772  0.11723187  0.27242945  0.87405932]
 [ 4.4463871   9.49996579  1.13692283  1.79396178  3.27835853]
 [ 3.07373022  0.55094944  0.18511615  0.37051245  0.75167737]
 [ 0.65362745  4.72692901  1.06898739  0.52820324  5.07513338]
 [ 0.81564771  0.90409766  4.1451215   3.51540711  0.70952386]
 [ 4.35423537  0.06990459  1.21221248  1.55253677  0.44155843]
 [ 2.29782437  0.42757803  1.41949937  0.49084372  1.60893408]
 [ 0.07650025  2.06166319  0.57990996  2.49236813  0.38526056]
 [13.01362204  1.15006888  1.45047992  3.57073905  0.52414139]
 [ 0.20202897  0.49331919  1.32663411  3.02788962  1.02330897]
 [ 0.54802059  0.27710652  2.35770144  0.15016256  1.40163426]
 [ 0.16585465  1.54908124  3.23091617  0.92829674  1.74142859]
 [ 0.49778196  0.56975883  1.95900674  1.41479876  2.29042977]
 [ 0.803178    5.67651212  0.79591753  1.14473137  0.68460263]
 [ 0.30837759  2.27571353  0.40841372  0.28868774  5.39

### (e)

In [12]:
mean_column = data.mean(axis=0)
sd_column = data.std(axis=0)
print("Mean:\n",mean_column)
print("Standard Deviation:\n",sd_column)

Mean:
 [1.76248725 2.01662931 1.7440337  1.33738132 1.61538304]
Standard Deviation:
 [2.12100253 2.29180175 2.2121953  1.07875404 1.75901322]


### (f)

In [14]:
normalized = (data-mean_column)/sd_column
normalized_mean = normalized.mean(axis=0)
normalized_sd = normalized.std(axis=0)
print("Mean of the normalized matrix:\n",normalized_mean)
print("Standard Deviation of the normalized matrix:\n", normalized_sd)

Mean of the normalized matrix:
 [2.04281037e-16 1.06581410e-16 8.88178420e-18 2.44249065e-16
 8.88178420e-17]
Standard Deviation of the normalized matrix:
 [1. 1. 1. 1. 1.]


# Question 3

### (a)

In [16]:
def vandermonde(N):
    vec = np.arange(N) + 1
    V = vec.reshape(N, 1) ** np.arange(N)
    return V

vander = vandermonde(12)
print(vander)

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

### (b)

In [18]:
x = np.ones(12)
print("x:\n", x)
b = vander.dot(x)
print("b:\n", b)

x:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
b:
 [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


### (c)

In [20]:
import numpy.linalg as lalg
v_invert = lalg.inv(vander)
res = np.dot(v_invert, b)
print(res)

[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


The expected outcome was a vector of all element to be equal to 1. Although Most of the results are equal to or nearer to 1, but some of the elements have differed much.

### (d)

In [21]:
res2 = lalg.solve(vander, b)
print(res2)

[0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]


All the Vector elements are either 1 or close to it.

GitHub Link:
https://github.com/SougataSenG/SougataSen_24-27-37.git